// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grocery_api.EfCore;

#nullable disable

namespace groceryapi.Migrations
{
    [DbContext(typeof(GroceryAppContext))]
    [Migration("20221228094639_InitializeData")]
    partial class InitializeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("grocery_api.Models.Grocery", b =>
                {
                    b.Property<string>("GroceryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroceryListID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("GroceryID");

                    b.HasIndex("GroceryListID");

                    b.ToTable("Groceries");
                });

            modelBuilder.Entity("grocery_api.Models.GroceryList", b =>
                {
                    b.Property<string>("GroceryListID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroceryListID");

                    b.ToTable("GroceryLists");
                });

            modelBuilder.Entity("grocery_api.Models.GroceryListGrocery", b =>
                {
                    b.Property<string>("GroceryListID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("GroceryID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.HasKey("GroceryListID", "GroceryID");

                    b.ToTable("GroceryListGroceries");
                });

            modelBuilder.Entity("grocery_api.Models.Grocery", b =>
                {
                    b.HasOne("grocery_api.Models.GroceryList", null)
                        .WithMany("Groceries")
                        .HasForeignKey("GroceryListID");
                });

            modelBuilder.Entity("grocery_api.Models.GroceryList", b =>
                {
                    b.Navigation("Groceries");
                });
#pragma warning restore 612, 618
        }
    }
}
