// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grocery_api.EfCore;

#nullable disable

namespace groceryapi.Migrations
{
    [DbContext(typeof(GroceryAppContext))]
    partial class GroceryAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("grocery_api.Models.Grocery", b =>
                {
                    b.Property<string>("GroceryID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroceryListID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("GroceryID");

                    b.HasIndex("GroceryListID");

                    b.ToTable("Groceries");

                    b.HasData(
                        new
                        {
                            GroceryID = "Bread",
                            Description = "Loaf of sliced rye bread",
                            Price = 2.99m
                        },
                        new
                        {
                            GroceryID = "Eggs",
                            Description = "12 large eggs",
                            Price = 3.99m
                        },
                        new
                        {
                            GroceryID = "Avocado",
                            Description = "1 Large hass avocado",
                            Price = 0.89m
                        },
                        new
                        {
                            GroceryID = "Milk",
                            Description = "1 Gallon of whole milk",
                            Price = 3.29m
                        },
                        new
                        {
                            GroceryID = "Apples",
                            Description = "1 lb of Honeycrisp apples",
                            Price = 2.99m
                        },
                        new
                        {
                            GroceryID = "Bananas",
                            Description = "1 lb of bananas",
                            Price = 0.89m
                        },
                        new
                        {
                            GroceryID = "Chicken Breast",
                            Description = "1 lb of raw chicken breast",
                            Price = 4.99m
                        });
                });

            modelBuilder.Entity("grocery_api.Models.GroceryList", b =>
                {
                    b.Property<string>("GroceryListID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroceryListID");

                    b.ToTable("GroceryLists");

                    b.HasData(
                        new
                        {
                            GroceryListID = "My List",
                            Owner = "Joshua Keel"
                        });
                });

            modelBuilder.Entity("grocery_api.Models.GroceryListGrocery", b =>
                {
                    b.Property<string>("GroceryListID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(1);

                    b.Property<string>("GroceryID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnOrder(2);

                    b.HasKey("GroceryListID", "GroceryID");

                    b.ToTable("GroceryListGroceries");
                });

            modelBuilder.Entity("grocery_api.Models.Grocery", b =>
                {
                    b.HasOne("grocery_api.Models.GroceryList", null)
                        .WithMany("Groceries")
                        .HasForeignKey("GroceryListID");
                });

            modelBuilder.Entity("grocery_api.Models.GroceryList", b =>
                {
                    b.Navigation("Groceries");
                });
#pragma warning restore 612, 618
        }
    }
}
